version: '3.9'

services:
  user-api:
    container_name: user-api
    image: user-api
    build:
      context: ../../
      dockerfile: build/Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - user-network
    depends_on:
      - user-db

  user-db:
    container_name: user-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - user-db:/data/db
    networks:
      - user-network

networks:
  user-network:
    name: user
    driver: bridge

volumes:
  user-db:
    name: user-db
    driver: local
