version: '3.7'

services:
  user-api:
    container_name: user-api
    image: user-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:80'
    environment:
      - MONGO_HOST=mongodb://user-db:27017
      - MONGO_USER_DATABASE=User
      - MONGO_USERS_COLLECTION=Users
    networks:
      - user-network
    depends_on:
      - user-db

  user-db:
    container_name: user-db
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      - user-network

networks:
  user-network:
    name: user-network
    driver: bridge

volumes:
  mongo:
