# localhost 5000 / docker 5001

###

# curl -X 'GET' 
#  'http://localhost:5001/search?query=yago' 
#  -H 'accept: application/json'
GET http://localhost:5001/search?query=yago
accept: application/json
Content-Type: application/json

###

# curl -X 'GET' 
#  'http://localhost:5001/search?query=yago&from=1&size=10' 
#  -H 'accept: application/json'
GET http://localhost:5001/search?query=yago&from=1&size=10
accept: application/json
Content-Type: application/json
